Refactored directories for Histogram and Brightness
deyuan/PIMeval-PIMbench pull request #63
Opened 2024-07-25 19:17 UTC by hugoabbot

all tested and working

2024-07-25 20:11 UTC, fasiddique requested changes
Thank you! 
Some minor comments. Also, could you please add cuda error checking for each cuda call, just like the vector add?

2024-07-25 20:11 UTC, fasiddique commented on PIMbench/cpp-brightness/baselines/CPU/brightness.cpp
> +  }
How are we verifying the CPU implementation?

2024-07-25 20:11 UTC, fasiddique commented on PIMbench/cpp-brightness/baselines/GPU/brightness.cu
> +  while ((opt = getopt(argc, argv, "h:i:v:")) >= 0)
```suggestion
  while ((opt = getopt(argc, argv, "h:i:v:b:")) >= 0)
```

2024-07-25 20:11 UTC, fasiddique commented on PIMbench/cpp-brightness/baselines/GPU/brightness.cu
> +  std::cout << "Input file : '" << fn << "'" << std::endl;
```suggestion
  std::cout << "Running brightness on GPU for input file : '" << fn << "'" << std::endl;
```

2024-07-25 20:11 UTC, fasiddique commented on PIMbench/cpp-histogram/README.md
> +The CPU variant of histogram has been implemented using standard C++ library and threading for parallel execution. Other C++ libraries, such as OpenBLAS or Boost, were not used as either histogram im
```suggestion
The CPU variant of histogram has been implemented using standard C++ library and pthread for parallel execution. Other C++ libraries, such as OpenBLAS or Boost, were not used as either histogram implementations did not exist or did fall not fall into the scope of our use case. Threading was chosen in favor of OpenMP as timings had no significant differences, and due to previous works, which we modeled our benchmarks after, using the same method.
```
Also mention that this code was taken from phoenix benchmark and was modified accordingly.

2024-07-25 20:11 UTC, fasiddique commented on PIMbench/cpp-histogram/baselines/CPU/hist.cpp
> +  std::cout << "Input file : '" << fn << "'" << std::endl;
```suggestion
  std::cout << "Running hostogram on CPU for input file : '" << fn << "'" << std::endl;
```

2024-07-25 22:08 UTC, fasiddique requested changes

2024-07-25 22:08 UTC, fasiddique commented on PIMbench/cpp-brightness/baselines/GPU/brightness.cu
> +  THRUST_CHECK();
Let's remove this also

2024-07-25 22:08 UTC, fasiddique commented on PIMbench/cpp-histogram/baselines/GPU/hist.cu
> +  }
```suggestion
```
I think following error checking will suffice.

2024-07-26 01:05 UTC, fasiddique reviewed
A minor change and it will be ready to merge!

2024-07-26 07:48 UTC, deyuan commented on PIMbench/cpp-brightness/baselines/CPU/brightness.cpp
> +  if (!fn.substr(fn.find_last_of(".") + 1).compare("bmp") == 0)
Please use C++ style and handle the case of no dot in file name:
if (fn.substr(fn.find_last_of(".")) != ".bmp")

2024-07-26 07:48 UTC, deyuan commented on PIMbench/cpp-brightness/baselines/GPU/brightness.cu
> +  if (!fn.substr(fn.find_last_of(".") + 1).compare("bmp") == 0)
Please use C++ style and handle the case of no dot in file name:
if (fn.substr(fn.find_last_of(".")) != ".bmp")

2024-07-26 07:50 UTC, deyuan commented on PIMbench/cpp-brightness/baselines/GPU/brightness.cu
> +  printf("This file has %ld bytes of image data with a brightness coefficient of %d\n", imgDataBytes, brightnessCoefficient);
Need to use %llu to print imgDataBytes

2024-07-26 07:50 UTC, deyuan commented on PIMbench/cpp-histogram/baselines/CPU/hist.cpp
> +  printf("This file has %ld bytes of image data, %ld pixels\n", imgDataBytes, imgDataBytes / NUMCHANNELS);
Need to use %llu to print both values

2024-07-26 07:51 UTC, deyuan commented on PIMbench/cpp-histogram/baselines/GPU/hist.cu
> +  printf("This file has %ld bytes of image data, %ld pixels\n", imgDataBytes, imgDataBytes / NUMCHANNELS);
Need to use %llu for both

2024-07-26 07:51 UTC, deyuan commented on PIMbench/cpp-brightness/baselines/CPU/brightness.cpp
> +  printf("This file has %ld bytes of image data with a brightness coefficient of %d\n", imgDataBytes, params.brightnessCoefficient);
Need %llu for imgDataBytes

2024-07-26 07:54 UTC, deyuan commented on PIMbench/cpp-brightness/Makefile
> +	$(MAKE) -C $@ $(MAKECMDGOALS) USE_OPENMP=$(USE_OPENMP)
Missing new line at the end

2024-07-26 07:55 UTC, deyuan commented on PIMbench/cpp-brightness/baselines/CPU/Makefile
> +	rm -rf $(EXEC)
Missing new line at the end

2024-07-26 07:56 UTC, deyuan commented on PIMbench/cpp-histogram/baselines/CPU/hist.cpp
> +  if (!fn.substr(fn.find_last_of(".") + 1).compare("bmp") == 0)
Same as above

2024-07-26 07:57 UTC, deyuan commented on PIMbench/cpp-histogram/baselines/GPU/hist.cu
> +  if (!fn.substr(fn.find_last_of(".") + 1).compare("bmp") == 0)
Same as above

2024-07-26 07:58 UTC, deyuan reviewed
Hi @hugoabbot please see my comments above and help to fix them

2024-07-26 19:02 UTC, fasiddique approved these changes
Thank you! This looks good to me. If @deyuan is ok, we can merge this.

2024-07-27 05:35 UTC, merged